### ISSUE TITLE
exception handling

### ISSUE THREAD

**Issue by o-jill** [o-jill/washcrus#132]
1. rescue
```ruby
rescue => e 
# is same as
rescue StandardError => e
```

2. how to put in detail
```ruby
begin
  func()
rescue => detail
  print detail.backtrace.join("\n")
end

# will say

prog.rb:2:in `a'
prog.rb:6:in `b'
prog.rb:10
```

**Comment by o-jill** [comment]
1 has been done.
but rubocop also warns parameter "e" is not used...

**Comment by o-jill** [comment]
2 has been done. 855aba2
