### ISSUE TITLE
error: sending mail w/ attached file.

### ISSUE THREAD

**Issue by o-jill** [o-jill/washcrus#135]
W, [2019-05-14T22:43:16.735815 #4873]  WARN -- : class=[ArgumentError] message=[wrong number of arguments (given 4, expected 3)] stack=[/var/www/html/cgi-bin/washcrus/util/mailmgr.rb:64:in `send_mailex_withfooter'
/var/www/html/cgi-bin/washcrus/move.rb:159:in `send_mail_finished'
/var/www/html/cgi-bin/washcrus/move.rb:209:in `send_mail'
/var/www/html/cgi-bin/washcrus/move.rb:264:in `register_move'
/var/www/html/cgi-bin/washcrus/move.rb:296:in `block in perform'
/var/www/html/cgi-bin/washcrus/game/taikyokudata.rb:201:in `block (2 levels) in lock'
/var/www/html/cgi-bin/washcrus/game/taikyokudata.rb:198:in `open'
/var/www/html/cgi-bin/washcrus/game/taikyokudata.rb:198:in `block in lock'
/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/var/www/html/cgi-bin/washcrus/game/taikyokudata.rb:197:in `lock'
/var/www/html/cgi-bin/washcrus/move.rb:282:in `perform'
/var/www/html/cgi-bin/washcrus/move.rb:311:in `<main>'] in move

**Comment by o-jill** [comment]
it's looks good after fixing syntax error:
```
I, [2019-05-22T19:03:04.209545 #5551]  INFO -- : gameid:3c3e2a80c8
I, [2019-05-22T19:03:04.209684 #5551]  INFO -- : sfen:ln1g1gsnl/1r1s2kb1/p1pp1p1pp/4p1p2/1p7/2PP4P/PPB1PPPP1/2SR2S2/LN1GKG1NL b - 15
I, [2019-05-22T19:03:04.209718 #5551]  INFO -- : move:%TORYO
D, [2019-05-22T19:03:04.209752 #5551] DEBUG -- : Move.initialized
D, [2019-05-22T19:03:04.223833 #5551] DEBUG -- : Move.read data
D, [2019-05-22T19:03:04.241877 #5551] DEBUG -- : Move.apply sfen, jmv
D, [2019-05-22T19:03:04.242012 #5551] DEBUG -- : Taikyokudata.move(jsmv, 2019-05-22 19:03:04 +0900)
D, [2019-05-22T19:03:04.242586 #5551] DEBUG -- : if jsmv[:special]
D, [2019-05-22T19:03:04.242633 #5551] DEBUG -- : @tkd.move() = 1
D, [2019-05-22T19:03:04.242824 #5551] DEBUG -- : tkd.finished(now, b == 'b')
D, [2019-05-22T19:03:04.242859 #5551] DEBUG -- : @jkf.setfinishdate()
D, [2019-05-22T19:03:04.242890 #5551] DEBUG -- : userdb = UserInfoFile.new
D, [2019-05-22T19:03:04.268857 #5551] DEBUG -- : tcdb.finished(@gameid)
D, [2019-05-22T19:03:04.272498 #5551] DEBUG -- : Move.sendmail
D, [2019-05-22T19:03:05.962257 #5551] DEBUG -- : Move.performed
```
not pushed and committed.
only fixed locally on working server.

**Comment by o-jill** [comment]
``` diff
diff --git a/util/mailmgr.rb b/util/mailmgr.rb
index 3f06756..8f90110 100644
--- a/util/mailmgr.rb
+++ b/util/mailmgr.rb
@@ -61,9 +61,9 @@ class MailManager
   # @param addr    メールアドレス
   # @param subject 件名
   # @param msg     本文
-  def send_mailex_withfooter(addr, subject, msg)
+  def send_mailex_withfooter(addr, subject, msg, attach)
     msg += MailManager.footer
-    send_mailex(addr, subject, msg)
+    send_mailex(addr, subject, msg, attach)
   end

   # 添付ファイル付きメールの送信
```

**Comment by o-jill** [comment]
fixed. c4f1de76f
