### ISSUE TITLE
saving marqueenews got error

### ISSUE THREAD

**Issue by o-jill** [o-jill/washcrus#185]
where:
index.rb?adminmqnewsupdate

error message:
```
Content-Type: text/html; charset=UTF-8
    ERROR:no implicit conversion of Hash into String
    STACK:/var/www/html/cgi-bin/washcrus/views/adminmqnewsupdate.rb:46:in `lines'
/var/www/html/cgi-bin/washcrus/views/adminmqnewsupdate.rb:46:in `put_marquee'
/var/www/html/cgi-bin/washcrus/views/adminmqnewsupdate.rb:67:in `show'
/var/www/html/cgi-bin/washcrus/washcrus.rb:157:in `adminmqnewsupdate'
/var/www/html/cgi-bin/washcrus/washcrus.rb:272:in `call'
/var/www/html/cgi-bin/washcrus/washcrus.rb:272:in `cmdtofunc'
/var/www/html/cgi-bin/washcrus/washcrus.rb:300:in `perform'
/var/www/html/cgi-bin/washcrus/index.rb:24:in `
```

comments:
i could save the content but i saw this error.

**Comment by o-jill** [comment]
commit 3711648 solved this issue.
