### ISSUE TITLE
firefox test failed on github actions

### ISSUE THREAD

**Issue by o-jill** [o-jill/washcrus#192]
draw behavior got error w/ firefox test on github actions.
```
travis_fold:start:draw.2draw test
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5: Unable to locate element: #btn_draw_suggest (Selenium::WebDriver::Error::NoSuchElementError)
	from NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5
	from element.find/</<@chrome://remote/content/marionette/element.js:305:16
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:547:in `find_element_by'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/search_context.rb:62:in `find_element'
	from /home/runner/work/washcrus/washcrus/travisci/testdraw.rb:19:in `drawbtn'
	from /home/runner/work/washcrus/washcrus/travisci/testdraw.rb:28:in `drawsuggest'
	from /home/runner/work/washcrus/washcrus/travisci/testdraw.rb:51:in `block in run'
	from /home/runner/work/washcrus/washcrus/travisci/testdraw.rb:48:in `each'
	from /home/runner/work/washcrus/washcrus/travisci/testdraw.rb:48:in `run'
	from travisci/browsertestmain.rb:89:in `<main>'
+ ret=1
+ [ 1 -ne 0 ]
+ cat ./log/newgamegenlog.txt
phase:okcan
phase:canok
phase:cancan
phase:okok
URL: http://localhost:3000/index.rb?login
'http://localhost:3000/index.rb?login' is not http://localhost:3000/index.rb?logincheck.
URL: http://localhost:3000/index.rb?login
'line two.
Top
News
Sign Up
Log In
Support
洗足池
Log in
e-mail
password
    パスワードを忘れた？

パスワードのリセット
©ぢるっち 2017-2021 with Ruby v2.6.8' does not match (?-mix:Logged in successfully).
place:/home/runner/work/washcrus/washcrus/travisci/testresult.rb:64:in `matchproperty'
/home/runner/work/washcrus/washcrus/travisci/testresult.rb:96:in `checkmatch'
/home/runner/work/washcrus/washcrus/travisci/browsertestabs.rb:138:in `checklogin'
/home/runner/work/washcrus/washcrus/travisci/testgame.rb:111:in `becomegote'
/home/runner/work/washcrus/washcrus/travisci/testdraw.rb:24:in `drawsuggest'
/home/runner/work/washcrus/washcrus/travisci/testdraw.rb:51:in `block in run'
/home/runner/work/washcrus/washcrus/travisci/testdraw.rb:48:in `each'
/home/runner/work/washcrus/washcrus/travisci/testdraw.rb:48:in `run'
travisci/browsertestmain.rb:89:in `<main>'
+ cat ./log/loginoutlog.txt
+ cat ./log/gamelog.txt
# Logfile created on 2021-09-26 13:16:19 +0000 by logger.rb/66358
D, [2021-09-26T13:16:19.256814 #2760] DEBUG -- : id1:97783c65 id2:bbf5fc78
D, [2021-09-26T13:34:32.596692 #5959] DEBUG -- : id1:97783c65 id2:bbf5fc78
# Logfile created on 2021-09-26 13:14:54 +0000 by logger.rb/66358
I, [2021-09-26T13:14:54.958200 #2524]  INFO -- : user bbf5fc78 login.
```

**Comment by o-jill** [comment]
you may have to add 'sleep' like ac031141 to keep some sequence.
